apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: backend
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx


'''
$ kubectl get pods --namespace=backend
No resources found in backend namespace.

$ kubectl apply -f namespace.yaml --namespace=backend
pod/nginx created

$ kubectl get pods --namespace=backend
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          37s

$ kubectl get pods --namespace=backend -o wide
NAME    READY   STATUS    RESTARTS   AGE   IP             NODE       NOMINATED NODE   READINESS GATES
nginx   1/1     Running   0          41s   10.244.0.121   minikube   <none>           <none>
'''